### ISSUE TITLE
Support NVDA 2021.1 compatibility

### ISSUE THREAD

**Issue by CyrilleB79** [lukaszgo1/nvda-ocr#9]
People on a French mailing list want to have a version compatible with NVDA 2021.1.

Could you also confirm that you are the current maintainer of OCR add-on. If yes, please modify the following page to reference yourself as the maintainer:
https://addons.nvda-project.org/addons/nvdacompat.en.html
I can do it for you if you do not have access to SRT.

**Comment by lukaszgo1** [comment]
I've announced a new release on add-ons mailing list and opened a PR against addonFiles. Just in case a direct link is: https://github.com/lukaszgo1/nvda-ocr/releases/download/v2.2/ocr-2.2.nvda-addon

Yes, I am a maintainer of the OCr add-on so the info on the compat web page should be updated. I don't have access to translation system so if you would be willing to do it for me that would be super helpful.
